# Generated by Django 6.0.4 on 2026-04-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("ip", models.GenericIPAddressField()),
                ("os", models.CharField(max_length=255)),
            ],
        ),
    ]
