# Generated by Django 6.0.4 on 2026-05-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_remove_job_schedule_remove_task_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='active_task_id',
        ),
        migrations.AlterField(
            model_name='job',
            name='client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to_run',
            field=models.DateTimeField(blank=True),
        ),
    ]
