# Generated by Django 6.0.4 on 2026-05-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0005_remove_task_time_to_run_job_time_to_run_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="time_to_run",
            field=models.DateTimeField(blank=True, default=1),
        ),
    ]
