# Generated by Django 6.0.4 on 2026-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0006_rename_job_type_task_task_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="repeat",
            field=models.CharField(default=None, null=True),
        ),
    ]
