# Generated by Django 6.0.5 on 2026-05-20 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0006_alter_job_time_to_run"),
        ("ui", "0007_job_repeat"),
    ]

    operations = []
